### PR TITLE
Add extras columns to bill versions and vote events.

### PR DESCRIPTION
**Pull request by jmcarp**
* Bill versions: https://github.com/openstates/openstates/pull/2368
* Vote events: see duplicate votes at http://bobsled.openstates.org/run-AZ-2018-06-12.html

### CODE REVIEW

**Comment by jmcarp** [comment]
WDYT @jamesturk ? Am I missing a migration or something?

**Comment by jamesturk** [comment]
Yep, generating this is a little tricky but you should be able to do
something like

django-admin --settings=pupa.settings makemigrations

**Comment by jmcarp** [comment]
@jamesturk: not sure why tests are failing now, but it looks unrelated to this change--apparently we're installing an older version of pytest that conflicts with pytest-django, but I'm not sure why. Any chance travis is caching dependencies?

**Comment by jamesturk** [comment]
I think the pre-installed py.test just wasn't being upgraded, I pinned the requirement to the latest pytest for now

**Pull request merged**
