### PR TITLE
split into opencivicdata.core and opencivicdata.legislative #83

### PR DESCRIPTION
**Pull request by jamesturk**
as discussed in #83 - figured proving the concept would be valuable

it is a pretty clean split, there's one quirky circular dependency related to the admin, but nothing that wasn't simple to solve with some conditional behavior that checks if legislative is installed

### CODE REVIEW

**Comment by jamesturk** [comment]
Changelog includes the only caveats I know of:

https://github.com/opencivicdata/python-opencivicdata-django/pull/85/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR8

basically migrating users will have to change their INSTALLED_APPS to include both apps and will have to run a fake migration

**Comment by jamesturk** [comment]
thoughts @jpmckinney & @fgregg ?  this would be a breaking change but the steps to update aren't too bad and I do think it'll make the future better as we go beyond the legislative

**Comment by fgregg** [comment]
Sorry, pretty covered up right now. Can you give me until middle of next week to review and think about this?

**Comment by jamesturk** [comment]
yeah, no rush on my end- just wanted y'all to see it

**Comment by jpmckinney** [comment]
I didn't read the diff thoroughly but it mostly looks like copy-pasting things between files, changing imports based on those moves, adding lines to ensure the database table names are unchanged, and a little try/catch in the admin to handle legislative not being present. Was there any part requiring special attention? Otherwise looks good to me.

**Comment by jamesturk** [comment]
that's all it does, I just wanted to clear the breaking change described here

https://github.com/opencivicdata/python-opencivicdata-django/pull/85/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR8

with you as it'll affect existing installations

**Comment by jpmckinney** [comment]
Yup, looks like the break is as minimal as can be :)

**Comment by gordonje** [comment]
Shouldn't each app (core, legislative, elections, etc.) have their own set of tests? 

And maybe this is related, but then wouldn't the constants and merge functions move into core?

**Comment by jamesturk** [comment]
Good point, I think there's more room to push things in that direction, but
fortunately that'll all be behind the scenes refactoring so I figured I'd
do the controversial/ public-facing stuff first.

I should find some time to move the tests into their respective modules,
I'm undecided on the merge code, since it (like divisions.py) sort of sits
outside the needs of any one django app.

**Comment by gordonje** [comment]
Seems like all the apps will depend on core, either directly or indirectly, in which case having merge in core makes it available to all the other apps. But, yeah, incremental steps.

I'm cool with merging this as is. Then, if you like, I can help move the tests into respective apps ahead of our PR for the elections models.

**Comment by jamesturk** [comment]
👍 if this works for datamade we'll go ahead

**Comment by fgregg** [comment]
Hi all,

So my concern is purely social and political. Up to now, having all of this in one repo hast meant that @jamesturk and @jpmckinney have been gatekeepers for the extensions to OCD that I, @gordonje, and @aepton have been pushing. 

While this has slowed development down, I think that this has ultimately led to a much better models. Since we are basically, in the data standard creation business here, that seems like the really correct trade off.

I well appreciate the technical benefits of this approved split, but I can also imagine it leading to a shift in organizational dynamics. It's easy to imagine that, as a bunch of busy folks, that we will tend not to scrutinize the repos that we do not use regularly. I think this would be net loss.

Now we are really talking about governance issues, and I know that there other things that to talk about in this regard, so maybe we should have a phone conversation about governance soon. I know that @djbridges is interested in talking about some governance issues as well (particularly around ocd-ids)

So... tldr, i'd like to have a clarification of how governance of reference implementations of OCD models accompany this technical change.

**Comment by jpmckinney** [comment]
Happy to join a call on governance and other socio-political questions.

**Comment by jamesturk** [comment]
Same, definitely something we should sort out.  Just sent an email to figure out timing.

As for this particular change- that concern about being able to just ignore the apps that were further from one's area(s) of interest was one of the reasons I landed on keeping this in one repo, but yeah it is def. still a risk as this grows to include more parts we aren't all using.

Are we OK with this change for now or would you rather wait?

**Comment by fgregg** [comment]
I'm okay with it. Give me a few hours, to pin some various dependencies though.

**Comment by jamesturk** [comment]
SGTM

**Comment by fgregg** [comment]
I'm good to go, @jamesturk

**Pull request merged**
