### PR TITLE
Stop updating OCDBase.updated_at on every save

### PR DESCRIPTION
**Pull request by antidipyramid**
## Overview

This PR amends the `OCDBase` model to no longer update `updated_at` on save. This change is necessary to begin using the `last_seen` property properly.

### Background

`OCDBase.updated_at` keeps track of when database items were last updated. Previously, we assumed that this timestamp should be updated automatically on every object save. 

### This PR

We will now be using a new `OCDBase.last_seen` [to keep track of when an object was last seen in a scrape](https://github.com/opencivicdata/pupa/issues/295). Since we can no longer assume that new information was found in a scrape every time an object is saved, `OCDBase.updated_at` longer updates automatically on save.

### CODE REVIEW

**Review by hancush — APPROVED** [review]
Makes sense to me, @antidipyramid. Would you mind adding a few things to the PR description to leave a clearer audit trail?

- [ ] Describe the overall approach here: What is the distinction between last_seen and last_updated? How will they be kept current? How does this change fit into the approach? 
- [ ] Specify whether these changes rely on any other PR/s, and add a reference to it/them, if applicable.
- [ ] Add references to any relevant issue/s. 

If these changes rely on other PRs, please also wait to merge until everything is ready to come in at once. We install this package from master, so we don't want to deploy anything until it's ready for primetime.

**Comment by antidipyramid** [comment]
@hancush No problem. 

Since this is just a change to `OCDBase`, I don't believe this PR depends on any other (but please correct me if I've got that wrong!). 

There is, however, [a pupa PR](https://github.com/opencivicdata/pupa/pull/342) that depends on this one.

**Comment by hancush** [comment]
@antidipyramid I'm thinking if you merge this, then the updated at field will stop updating when objects are saved, since you've changed it to auto_add_now. Does that seem right to you?

**Comment by antidipyramid** [comment]
@hancush That does seem correct. The only thing is that I don't believe the new test for the `last_seen` field in the pupa PR will not pass until the changes in this PR are merged.

**Comment by hancush** [comment]
@antidipyramid Can you install from this branch, to incorporate the changes?

**Comment by antidipyramid** [comment]
@hancush As in locally? Yes, I can. When I do that, all tests pass.

**Comment by hancush** [comment]
@antidipyramid That's good news! Can you update the requirements in your pupa branch to install python-opencivic data from this branch, so the tests there pass?

**Pull request merged**
