### PR TITLE
split opencivicdata.events into own app

### PR DESCRIPTION
**Pull request by jamesturk**
Trying to make this a bit more granular, migration to this will involve running migrate once with --fake-initial (which skips creation of tables that already exist).  Because of the legislative.0013 migration setting managed=False on the legislative app's version of events Django will not delete the tables (and resumes managing them once events.0001 runs).

### CODE REVIEW

**Comment by jamesturk** [comment]
@fgregg no actual code changes in this but it would require you to update your settings and run migrations so wanted to flag it for your review

**Comment by fgregg** [comment]
this will a pain for me to adapt to, so that may be coloring my views on this.

right now we have three apps, core, legislative, and elections. with this dependency graph

core
core -- elections
core -- legislative

with this change we will have a graph like

core
core -- elections
core -- legislative
core -- legislative -- events (because events requires a few models from legislative)

i think it's a bit confusing to make events an app at the same level that have different dependency structure.

Would probably be mainly ameliorated if you changed the name to legislative_events.

**Comment by fgregg** [comment]
if we could delay doing this, that would be be break, it would be a pretty breaking change for a lot of things (including pupa)

**Comment by jamesturk** [comment]
Understood about the naming, but want to clarify -what is breaking about this change (for pupa or otherwise) in your view?

**Comment by fgregg** [comment]
We'll have to update all the imports like 

https://github.com/opencivicdata/pupa/blob/c0dbe820821caa66f1cb02675dfdcd3df22307b7/pupa/importers/events.py#L3

unless, I missed something.

```

from opencivicdata.legislative.models import (Event, EventLocation, EventSource, EventDocument,
                                              EventDocumentLink, EventLink, EventParticipant,
                                              EventMedia, EventMediaLink, EventAgendaItem,
                                              EventRelatedEntity, EventAgendaMedia,
                                              EventAgendaMediaLink)
```

**Comment by jamesturk** [comment]
Ah yes, that is the one required change that I'm intending, wanted to make
sure it wasn't anything else.

I'm OK waiting.  TBH I'm waffling on Open States' continued use of these
models, I feel like it is likely time for us to diverge based on new needs.

**Comment by fgregg** [comment]
oh really, that's interesting. what do you think you are going to do instead?

**Comment by fgregg** [comment]
wait, do you mean

OS's use of the event models or OS's use of the ocd models?

**Comment by jamesturk** [comment]
The latter.

Nothing solid yet, but more and more finding things we're doing hamstrung
by the OCD models, without any real benefit coming from the uniformity.

simple example: if we had the Jurisdiction/Org structure as a static data
structure that changed when states made major constitutional changes those
lookups would be free as opposed to querying our database to make sure that
49 states are still bicameral however many times a day we wind up doing
that (even with caching)

but also in terms of moving faster, we're finally getting around to
incremental updates and we're either going to live off a long-running fork
of pupa or wind up just replacing it for those cases (which we've already
done for our person data processing), at that point very little will be
flowing through it

**Comment by fgregg** [comment]
that's so interesting, i've been increasingly appreciating the constraints.

**Pull request closed without merging**
