### PR TITLE
fix: django.contrib.postgres.fields.JSONField causes an error in Django 4.2 (fields.E904) https://docs.djangoproject.com/en/4.2/ref/checks/

### PR DESCRIPTION
**Pull request by jpmckinney**

### CODE REVIEW

**Review by fgregg — APPROVED** [review]

**Review by fgregg — CHANGES_REQUESTED** [review]
@jpmckinney would you mind fixing the tests?

**Comment by jpmckinney** [comment]
@fgregg All green now.

**Comment by fgregg** [comment]
thanks for this, @jpmckinney. hope all is well with you

**Comment by jpmckinney** [comment]
All good here :) It looks like the commit to roll the version to 3.3.1 is not on master. It was also tagged a "v3.3.1" (like v3.3.0). However, the other tags omit the "v".

Okay for me to tag and release as "3.4.0" ?

**Comment by fgregg** [comment]
go for it!

**Comment by jpmckinney** [comment]
Ah, I see why the "v" was included - the workflow only runs on "v*" tags. I'll use it.

**Pull request merged**
